version: '3.8'

services:
  monitoring-service:
    container_name: monitoring-service
    build:
      context: ./      # контекст — текущая папка (monitoring-service)
      dockerfile: Dockerfile
    image: monitoring-service-image
    ports:
      - "8001:80"

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: gateway-service-image
    environment:
      - counting_service_url=http://monitoring-service
    ports:
      - "8000:80"
